### ISSUE TITLE
[feature] 增加 docker-compose 部署方式和 k8

### ISSUE THREAD

**Issue by hexonal** [ppoonk/AirGo#1]

**Comment by ezrawic4j** [comment]
同求

**Comment by lotusnetwork** [comment]
速通了

docker compose, 前端需要你自己搞定

https://github.com/lotusnetwork/Airgo-docker

**Comment by ezrawic4j** [comment]
> 速通了
> 
> docker compose, 前端需要你自己搞定
> 
> https://github.com/lotusnetwork/Airgo-docker

泰酷辣 为啥前端不一起搞了

**Comment by lotusnetwork** [comment]
> > 速通了
> > docker compose, 前端需要你自己搞定
> > https://github.com/lotusnetwork/Airgo-docker
> 
> 泰酷辣 为啥前端不一起搞了

因为这是速通 可能之后再玩一玩 现在在写给v2b hysteria2的后端支持 比较忙

**Comment by ezrawic4j** [comment]
> > > 速通了
> > > docker compose, 前端需要你自己搞定
> > > https://github.com/lotusnetwork/Airgo-docker
> > 
> > 
> > 泰酷辣 为啥前端不一起搞了
> 
> 因为这是速通 可能之后再玩一玩 现在在写给v2b hysteria2的后端支持 比较忙

大佬牛逼

**Comment by lotusnetwork** [comment]
> > > > 速通了
> > > > docker compose, 前端需要你自己搞定
> > > > https://github.com/lotusnetwork/Airgo-docker
> > > 
> > > 
> > > 泰酷辣 为啥前端不一起搞了
> > 
> > 
> > 因为这是速通 可能之后再玩一玩 现在在写给v2b hysteria2的后端支持 比较忙
> 
> 大佬牛逼

那个速通的讲真的非常烂 后面再摸吧
