### ISSUE TITLE
可否加入外网内网端口不同的选项？

### ISSUE THREAD

**Issue by 86pandapan** [ppoonk/AirGo#10]
今天发现，稳定一周的梯子突然连不上了。排查发现，是非标端口连不上了。用其他面板见过在前端设置外网连接和内网连接的选项，通过反代等方式实现80 443之类的标准端口也能连接。您参考哈

**Comment by ppoonk** [comment]
可以在节点编辑-中转ip和端口，填入你下发客户端的ip和端口(80或者443等)，上面节点信息里填后端监听的端口(需要反代的端口)
