### ISSUE TITLE
上TG啊 新版本有几个问题 

### ISSUE THREAD

**Issue by cnmars** [ppoonk/AirGo#12]
界面好看了  
1、新增加充值和非订阅商品保存按钮没反应
2、注册新用户 提交到数据库只有前缀 变没有带邮件后缀  admin@qq.com提交到数据库是admin 这样 
3、部署完可以登陆  退出不能登陆 数据库查询发现管理员密码字段为空
4、节点不显示 只显示到期时间和剩余流量

以上为SQLITE数据库测试 在有问题 在说

**Comment by ppoonk** [comment]
谢谢反馈，还没搞完，还有好几个地方需要改改。

**Comment by cnmars** [comment]
你TG呢

**Comment by cnmars** [comment]
> 谢谢反馈，还没搞完，还有好几个地方需要改改。

还有一个节点不显示 只显示到期时间和剩余流量

**Comment by ppoonk** [comment]
> > 谢谢反馈，还没搞完，还有好几个地方需要改改。
> 
> 还有一个节点不显示 只显示到期时间和剩余流量

问题1，2，4已修复，3没有复现。晚点编译新版本您在试试

**Comment by cnmars** [comment]
3你注册后可以正常登陆新的用户？ TG群给我管理员 我那个号没了

**Comment by cnmars** [comment]
刚测试了 节点显示 是修复了 
1、增加普通商品和充值还是没反应 
2、 首页普通用户注册还是没有带邮箱后缀  我注册admin123@qq.com 后台看到的是admin123
