### ISSUE TITLE
【建议】git提交可以增加细粒度，方便大家参与

### ISSUE THREAD

**Issue by PineappleBeer** [ppoonk/AirGo#14]
目前提交都是一次一大堆，这样也不知道更新了什么新功能和功能开发的进度。
如果提交时可以分多次且有详细的git message，大家可以参与开发了。

**Comment by ppoonk** [comment]
这个是因为还在开发中，改的东西比较多，我以后注意

**Comment by ppoonk** [comment]
这个是因为还在开发中，改的东西比较多，我以后注意
