### ISSUE TITLE
hysteria2中allowInsecure应该改为insecure

### ISSUE THREAD

**Issue by litecn** [ppoonk/AirGo#15]
hy2订阅后，配置中的allowInsecure设为ture，但v2rayN等导入后，配置还是false，生成订阅时应该修改成：
```
	case "hy2":
		values.Add("sni", node.Sni)
		if node.AllowInsecure {
			values.Add("insecure", "1")
		}

```
![image](https://github.com/ppoonk/AirGo/assets/4434111/43018adb-e33f-4a58-b75a-d89c38f9ad87)

这样修改后，自己编译测试过几个hy2的客户端都正常，v2rayN, Furious, Hiddify Next, NekoBox for Android都可正常导入订阅。

**Comment by ppoonk** [comment]
感谢反馈，方便的话您可以提交pr，我会合并。

**Comment by litecn** [comment]
fixed
