### ISSUE TITLE
老版本直接升级失败

### ISSUE THREAD

**Issue by 86pandapan** [ppoonk/AirGo#17]
从去年的版本，通过命令行直接升级的，然后就报错了。
重新安装，直接导入数据库，就报错。只能重新配置了。

另外请教一下，如何挂证书呢？系统里面没看到有，BT里面挂不生效呀

**Comment by ppoonk** [comment]
证书放在AirGo二进制同目录，并改名为 air.cer 和 air.key，暂时系统里面还没有设置证书的选项。
