### ISSUE TITLE
商店 项目显示异常

### ISSUE THREAD

**Issue by IMZCC** [ppoonk/AirGo#18]
后端使用Docker,版本latest
前端使用main分支, 部署在cloudflare pages

PC Web下显示异常:
![Clip_2024-03-18_14-15-19](https://github.com/ppoonk/AirGo/assets/25655983/ef079660-f121-45b4-8c4a-3ed4f9ceb081)

Mobile下显示正常:
![Clip_2024-03-18_14-17-33](https://github.com/ppoonk/AirGo/assets/25655983/e94f1abe-6da4-44b5-97fe-fe05a3347732)

**Comment by ppoonk** [comment]
收到，谢谢反馈！
