### ISSUE TITLE
[feature] 添加 USDT 支付方式

### ISSUE THREAD

**Issue by 3Kmfi6HP** [ppoonk/AirGo#2]
现有的支付宝当面付不安全，推荐添加 usdt 或者加密货币的支付方式

**Comment by ezrawic4j** [comment]
同求

还有易支付

**Comment by ppoonk** [comment]
好的，但是这个项目是个人爱好，我现在只有晚上或者有空才写代码。所以这个功能可能得过一段时间才加上。

> 现有的支付宝当面付不安全，推荐添加 usdt 或者加密货币的支付方式

**Comment by ppoonk** [comment]
> 同求
> 
> 还有易支付

2.1.6版本易支付已添加

**Comment by hulisang** [comment]
可以加个V免签吗，求求求
