### ISSUE TITLE
docker启动报错

### ISSUE THREAD

**Issue by wanliyunyan** [ppoonk/AirGo#21]
我可能没有看明白文档，我创建了config.yaml文件，这里面 db-name 这个需要修改吗？  
启动docker的时候报错
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint airgo (c7dc36f496a80e112bff4cda0d6f27670bc8aaeccbd46075f158896e105b4591):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 443 -j DNAT --to-destination 172.17.0.2:443 ! -i docker0: iptables: No chain/target/match by that name.
```

**Comment by ppoonk** [comment]
如果使用mysql的话，db-name就填成你数据库的名字。从错误消息看，不像是AirGo的问题，建议您google一下错误消息，或者检查并修改一下配置文件，重新部署看看。

**Comment by wanliyunyan** [comment]
我没有找到创建数据库的sql语句呢，我感觉我得先用脚本创建数据库，然后再给数据库一个名字，但是没有找到创建的脚本

**Comment by ppoonk** [comment]
如果使用mysql，需要您手动创建mysql数据库，可以通过宝塔面板、1panel面板，或者类似于Navicat的客户端创建。然后在config.yaml里修改数据库参数为刚创建的数据库。
