### ISSUE TITLE
clash配置文件中的规则 rule-providers 跑路了 导致配置无规则 访问应direct访问的网站时全走了代理

### ISSUE THREAD

**Issue by shuangyu233** [ppoonk/AirGo#22]
clash配置文件中的规则 rule-providers 跑路了 导致无规则  访问应direct访问的网站时全走了代理
如图所示
![20240325183119](https://github.com/ppoonk/AirGo/assets/63851113/1fe95c11-d8f1-46be-8a0f-68516b7b13d4)
![20240325183559](https://github.com/ppoonk/AirGo/assets/63851113/a351704d-d5c6-48d7-baeb-a36539a98142)

**Comment by ppoonk** [comment]
收到，感谢反馈

**Comment by ppoonk** [comment]
已修复，请新版发布后再重试看看。
