### ISSUE TITLE
节点→修改节点→访问控制中勾选的内容保存后 再次打开取消勾选 再点击确定 再重新点开编辑发现其仍处于勾选状态 且依旧生效

### ISSUE THREAD

**Issue by shuangyu233** [ppoonk/AirGo#23]
节点→修改节点→访问控制中勾选的内容保存后 再次打开取消勾选 再点击确定 再重新点开编辑发现其仍处于勾选状态 且依旧生效
![20240325184156](https://github.com/ppoonk/AirGo/assets/63851113/79bf91a3-ae62-4c06-8f6f-07126dd9b3f7)

**Comment by ppoonk** [comment]
收到，感谢反馈，有时间我测试看看

**Comment by shuangyu233** [comment]
并且该规则无法删除
![1](https://github.com/ppoonk/AirGo/assets/63851113/2eb1f73b-7943-466b-9d99-11cde5d3d74d)

**Comment by ppoonk** [comment]
> 并且该规则无法删除 ![1](https://private-user-images.githubusercontent.com/63851113/317258741-2eb1f73b-7943-466b-9d99-11cde5d3d74d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjgwOTgsIm5iZiI6MTcxMTYyNzc5OCwicGF0aCI6Ii82Mzg1MTExMy8zMTcyNTg3NDEtMmViMWY3M2ItNzk0My00NjZiLTlkOTktMTFjZGU1ZDNkNzRkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDEyMDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNGU3NDNhNTM2OGFhNWI5ZWQzYzQxZjA5MzAyZGI3ZWZmZjg5N2NhYTA2MzA2YWMwYzhhYzQ5YzNiNTUzOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z_Y1Art6_KSeU94_Ow-1qOb1InUvCBRcVPxNj7zhod0)

已修复，请新版发布后再重试看看。
