### ISSUE TITLE
前端docker 支持

### ISSUE THREAD

**Issue by shaxiaozz** [ppoonk/AirGo#28]
请问有计划推出前端的docker image吗

**Comment by ppoonk** [comment]
可以考虑，感谢提供意见

**Comment by ppoonk** [comment]
经过考虑，如果单纯做成docker镜像，会增加用户使用成本，包括 nginx配置，ssl证书，后端api接口地址等。不如直接使用宝塔面板或者1panel来部署前端静态资源。所以暂时不考虑做。
