### ISSUE TITLE
节点名称中携带国家图标

### ISSUE THREAD

**Issue by shaxiaozz** [ppoonk/AirGo#29]
![bfb875813ff5f34f791785bdd932b35](https://github.com/ppoonk/AirGo/assets/43721571/d6c9e58c-9952-455b-928c-d133594c198a)

**Comment by shuangyu233** [comment]
您的意思是让它不显示吗，以及这是哪个客户端？

**Comment by shaxiaozz** [comment]
找到方式了。国旗是unicode字符，谢谢~
