### ISSUE TITLE
前端部署报错，以下是vercel的log

### ISSUE THREAD

**Issue by mjjonone** [ppoonk/AirGo#3]
[23:20:10.737] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[23:20:10.851] Cloning ...(Branch: v2, Commit: a6c676a)
[23:20:10.861] Skipping build cache, deployment was triggered without cache.
[23:20:11.378] Cloning completed: 526.194ms
[23:20:11.631] Running "vercel build"
[23:20:12.174] Vercel CLI 32.2.3
[23:20:12.809] sh: vite: command not found
[23:20:12.815] Error: Command "vite build" exited with 127
部署时的选项，后端地址  air--air--fz8wm2jmpv6r.code.run
![uTools_1694791373895](https://github.com/ppoonk/AirGo/assets/142796823/2f3d1671-7d64-4ab7-b0c5-ec598c0c4b51)
![uTools_1694791653628](https://github.com/ppoonk/AirGo/assets/142796823/00a0f015-80f2-4df3-be27-eb9319bfdb0c)
不清楚是否需要在后面加上/api/

**Comment by ppoonk** [comment]
> [23:20:10.737] Running build in Washington, D.C., USA (East) – iad1 (Hive) [23:20:10.851] Cloning ...(Branch: v2, Commit: [a6c676a](https://github.com/ppoonk/AirGo/commit/a6c676a9b94b07928b0676d83843e3bd98ea0c7f)) [23:20:10.861] Skipping build cache, deployment was triggered without cache. [23:20:11.378] Cloning completed: 526.194ms [23:20:11.631] Running "vercel build" [23:20:12.174] Vercel CLI 32.2.3 [23:20:12.809] sh: vite: command not found [23:20:12.815] Error: Command "vite build" exited with 127 部署时的选项，后端地址 air--air--fz8wm2jmpv6r.code.run ![uTools_1694791373895](https://user-images.githubusercontent.com/142796823/268325203-2f3d1671-7d64-4ab7-b0c5-ec598c0c4b51.png) ![uTools_1694791653628](https://user-images.githubusercontent.com/142796823/268327877-00a0f015-80f2-4df3-be27-eb9319bfdb0c.png) 不清楚是否需要在后面加上/api/

非常抱歉，由于我的失误，wiki中的vercel部署截图不是完整的，我现在修改了一下，您再看看。
![image](https://telegraph-image.pages.dev/file/4f352a36513f517ff859a.png)

**Comment by ppoonk** [comment]
> > [23:20:10.737] Running build in Washington, D.C., USA (East) – iad1 (Hive) [23:20:10.851] Cloning ...(Branch: v2, Commit: [a6c676a](https://github.com/ppoonk/AirGo/commit/a6c676a9b94b07928b0676d83843e3bd98ea0c7f)) [23:20:10.861] Skipping build cache, deployment was triggered without cache. [23:20:11.378] Cloning completed: 526.194ms [23:20:11.631] Running "vercel build" [23:20:12.174] Vercel CLI 32.2.3 [23:20:12.809] sh: vite: command not found [23:20:12.815] Error: Command "vite build" exited with 127 部署时的选项，后端地址 air--air--fz8wm2jmpv6r.code.run ![uTools_1694791373895](https://user-images.githubusercontent.com/142796823/268325203-2f3d1671-7d64-4ab7-b0c5-ec598c0c4b51.png) ![uTools_1694791653628](https://user-images.githubusercontent.com/142796823/268327877-00a0f015-80f2-4df3-be27-eb9319bfdb0c.png) 不清楚是否需要在后面加上/api/
> 
> 非常抱歉，由于我的失误，wiki中的vercel部署截图不是完整的，我现在修改了一下，您再看看。 ![image](https://camo.githubusercontent.com/93f3d1e6fc730d91d08d1d52ff838963c6bf42f57098b16d90c755523e1c3705/68747470733a2f2f74656c6567726170682d696d6167652e70616765732e6465762f66696c652f3466333532613336353133663531376666383539612e706e67)

api地址是需要加/api/的，类似 http://192.168.0.8:80/api/

**Comment by mjjonone** [comment]
是我对vercel不熟悉，没有发现Root Directory 是构建目录，在vercel失败后，我到cloudflare page 成功部署，cf page的运行配置我知道，需要填构建目录。同时docker 镜像已经打包好，在我仓库里面有相关文件，希望作者可以给个标准的docker版本，经过测试，能单独运行到云paas平台上。第一个issue里面的启动命令没有start,害我排查半天，经过查看作者你的install.sh才发现。
前后端的深色模式开启，没有效果变化，不懂这个深色模式是黑夜模式还是根据什么判断自动开启。

**Comment by ppoonk** [comment]
> 是我对vercel不熟悉，没有发现Root Directory 是构建目录，在vercel失败后，我到cloudflare page 成功部署，cf page的运行配置我知道，需要填构建目录。同时docker 镜像已经打包好，在我仓库里面有相关文件，希望作者可以给个标准的docker版本，经过测试，能单独运行到云paas平台上。第一个issue里面的启动命令没有start,害我排查半天，经过查看作者你的install.sh才发现。 前后端的深色模式开启，没有效果变化，不懂这个深色模式是黑夜模式还是根据什么判断自动开启。

非常感谢你的支持和docker相关工作。docker版本我正在写，不久可能就会发布。
前端我用的[vue-next-admin框架](https://lyt-top.gitee.io/vue-next-admin-doc-preview/config/)，你说的这个深色模式我可能刚开始开发时，为了简单，直接删了相关代码，可能是这样，回头再详细看看。或者你去他的github看看相关代码。
