### ISSUE TITLE
package.json missing 'highlight.js' 'prismjs' and 'uuid'

### ISSUE THREAD

**Issue by tiansin** [ppoonk/AirGo#36]
@ppoonk RT

**Comment by ppoonk** [comment]
删掉package-lock.json和node_modules文件夹，再重新安装依赖看看

**Comment by tiansin** [comment]
> 删掉package-lock.json和node_modules文件夹，再重新安装依赖看看

好像可以了,个人还是建议把那些直接引用的包给加进去,免得出一些莫名奇妙的问题.
