### ISSUE TITLE
GetUserOrders接口切换分页有问题

### ISSUE THREAD

**Issue by tiansin** [ppoonk/AirGo#39]
我的订单列表,切换分页到第二页时,这个接口返回的total值会是0,导致前端又会再次请求一次接口,自动跳回第一页去.目测其它类似接口也有这个问题.

**Comment by tiansin** [comment]
看了下原因是Where写在Count之前了. https://github.com/ppoonk/AirGo/blob/95868b003e93361245ec10e93adc021e5e97abe5/server/service/user_order.go#L309

**Comment by ppoonk** [comment]
已收到反馈，感谢

**Comment by tiansin** [comment]
这句代码位置给放错了
https://github.com/ppoonk/AirGo/blob/95868b003e93361245ec10e93adc021e5e97abe5/server/service/user_order.go#L361

**Comment by ppoonk** [comment]
> 这句代码位置给放错了
> 
> https://github.com/ppoonk/AirGo/blob/95868b003e93361245ec10e93adc021e5e97abe5/server/service/user_order.go#L361



> 这句代码位置给放错了
> 
> https://github.com/ppoonk/AirGo/blob/95868b003e93361245ec10e93adc021e5e97abe5/server/service/user_order.go#L361

收到反馈，谢谢

**Comment by tiansin** [comment]
这段和下面那段的message写反了
https://github.com/ppoonk/AirGo/blob/4defa82bff3081121d070e43c1104a711e95be90/web/src/views/admin/order/dialog_edit.vue#L23

**Comment by ppoonk** [comment]
> 这段和下面那段的message写反了
> 
> https://github.com/ppoonk/AirGo/blob/4defa82bff3081121d070e43c1104a711e95be90/web/src/views/admin/order/dialog_edit.vue#L23

👍谢谢
