### ISSUE TITLE
[bug] 开启邮箱注册，需要验证码，注册按钮消失

### ISSUE THREAD

**Issue by mjjonone** [ppoonk/AirGo#4]
![uTools_1694852398847](https://github.com/ppoonk/AirGo/assets/142796823/daa494d2-abed-4195-b555-73ffceef0a09)
![uTools_1694852603510](https://github.com/ppoonk/AirGo/assets/142796823/2df78cf8-db55-4de3-b26c-66ef33239653)
导致无法注册

关闭后注册出现
![uTools_1694852761861](https://github.com/ppoonk/AirGo/assets/142796823/c43aed0e-816d-4521-a41e-9f5ebe3b3d44)
![uTools_1694852807078](https://github.com/ppoonk/AirGo/assets/142796823/2a3ac918-a3b0-4bf7-9ed6-28b73279f17a)

**Comment by mjjonone** [comment]
新[BUG] 关闭验证后，注册成功，后台能看见用户信息，但是登录提示，无法登录

![uTools_1694853207501](https://github.com/ppoonk/AirGo/assets/142796823/5d30891b-1bcb-4a10-8226-0b3e3a985ead)

**Comment by ppoonk** [comment]
第一个问题可能是div高度导致的，第二个稍等我去测试看看

**Comment by ppoonk** [comment]
> 新[BUG] 关闭验证后，注册成功，后台能看见用户信息，但是登录提示，无法登录
> 
> ![uTools_1694853207501](https://user-images.githubusercontent.com/142796823/268437989-5d30891b-1bcb-4a10-8226-0b3e3a985ead.png)

第二个问题我测试，无法复现，会不会你密码输错了？如果还有问题你录个视频发我邮箱。ponkpoiuty@gmail.com

**Comment by mjjonone** [comment]
经过复现，一开始我是开启邮箱验证，因为后面已经有了邮箱后缀，只输入前面，会有以下提示
![uTools_1694915796696](https://github.com/ppoonk/AirGo/assets/142796823/30067fe1-3dc0-4a77-8cd2-c4a01fd36e5f)
如果完整输入，才能接收到验证码邮件
![uTools_1694915840063](https://github.com/ppoonk/AirGo/assets/142796823/447382b0-26b2-4187-b96f-045f44e89a20)
所以，再关闭验证码后，我也是完整输入邮箱地址，也提示注册成功，但是经过你的提醒，进入后台发现邮箱信息是xxx@xxx@xxx
所以导致用户信息不存在

**Comment by mjjonone** [comment]
所以因为显示问题，无法知道如果用验证码注册后的用户信息的邮箱是否也是xxx@xx@xx,可以给程序加一个更新功能，方便更新
关于面板的共享节点功能没有看懂，只有管理员能看见信息，节点信息我感觉没全，而且也没有快捷分享的功能，在节点状态也没有共享节点，普通用户也看不到。
![uTools_1694916312249](https://github.com/ppoonk/AirGo/assets/142796823/1f362afb-ccf5-4109-9b7e-01f520aa8c76)

![uTools_1694916485098](https://github.com/ppoonk/AirGo/assets/142796823/273d9468-c5d4-4af2-be56-b117fafc48ca)
![uTools_1694916507184](https://github.com/ppoonk/AirGo/assets/142796823/3a39a95e-9b93-4a15-8e00-2297b6405544)

**Comment by mjjonone** [comment]
其实用户的ui也需要改善，不应该出现超级管理员的功能界面，不过对前期来说不是很急迫，如果作者有时间再后面慢慢完善，修改逻辑。
