### ISSUE TITLE
订阅配置文件名称自定义

### ISSUE THREAD

**Issue by dabige-nobody** [ppoonk/AirGo#41]
使用订阅地址下载到配置文件后，配置文件名称是一长串英文，能否自定义配置文件。例如叫Airgo。
![image](https://github.com/ppoonk/AirGo/assets/168285240/cd8ce6f5-6a4c-48cf-acf9-63779bbd4aa7)

**Comment by ppoonk** [comment]
收到反馈，这边有时间再看看
