### ISSUE TITLE
订阅规则集自定义

### ISSUE THREAD

**Issue by dabige-nobody** [ppoonk/AirGo#42]
能否新增一个配置文件参数，可自定义每个订阅类型的规则集？

![image](https://github.com/ppoonk/AirGo/assets/168285240/53587faa-781b-4291-81f6-b23d6e2b0c05)

例如新增一些常用的规则集。通过配置文件判断是否开启。
https://github.com/Loyalsoldier/clash-rules

**Comment by ppoonk** [comment]
收到反馈，有时间再看看
