### ISSUE TITLE
Surge 客户端订阅能否支持obfs混淆

### ISSUE THREAD

**Issue by dabige-nobody** [ppoonk/AirGo#43]
观察到Quantumult客户端订阅支持obfs混淆，请求Surge 客户端订阅能否也支持？

![image](https://github.com/ppoonk/AirGo/assets/168285240/7abba1b4-b518-44ae-a624-f5a4f5f0c9b8)

**Comment by ppoonk** [comment]
收到反馈，有时间再看看Surge的文档，看看能否添加
