### ISSUE TITLE
一个订阅地址支持所有订阅类型

### ISSUE THREAD

**Issue by dabige-nobody** [ppoonk/AirGo#44]
一个订阅地址支持所有订阅类型，看了下订阅类型在下载配置文件时，携带了http_user_agent进来。因此在订阅的controer中可以去做一定的判断。从而生成一个链接支持所有订阅类型。。

如果您同意这个需求，我将着手进行代码修改。创建一个PR。

**Comment by ppoonk** [comment]
可以的，欢迎你的pr！

**Comment by sylvan99** [comment]
0.29订阅扫出来密码不对

**Comment by dabige-nobody** [comment]
抱歉，看到这段代码了。应该默认就是支持一个订阅连接识别不同客户端的了
![image](https://github.com/ppoonk/AirGo/assets/168285240/8655bd64-ef0d-4f1e-b8f4-c473432e4470)
