### ISSUE TITLE
新增用户时报错

### ISSUE THREAD

**Issue by BestWaveRock** [ppoonk/AirGo#5]
<img width="1301" alt="图片" src="https://github.com/ppoonk/AirGo/assets/36351805/99076b01-5513-4636-a8de-2fc4fc757e12">

**Comment by ppoonk** [comment]
确实是个小bug，是订阅到期时间为空导致的，下个版本修复。目前新建用户的时候，尽量把信息都填上，可以避免这类问题。

**Comment by ppoonk** [comment]
确实是个bug，马上修复

**Comment by BestWaveRock** [comment]
赞👍🏻

ppoonk ***@***.***> 于2023年9月19日周二 22:06写道：
