### ISSUE TITLE
请问支持reality吗

### ISSUE THREAD

**Issue by jiayihello** [ppoonk/AirGo#7]
请问支持reality吗

**Comment by ppoonk** [comment]
支持，但是得用适配的XrayR，暂时没有合并到XrayR主分支，详情：[对接XrayR](https://github.com/ppoonk/AirGo/wiki/AirGo-Wiki#3-%E5%AF%B9%E6%8E%A5xrayr%E7%AD%89%E5%90%8E%E7%AB%AF)。欢迎测试反馈。

**Comment by jiayihello** [comment]
[2-1-1 安装AirGo核心](https://github.com/ppoonk/AirGo/wiki/AirGo-Wiki#2-1-1-%E5%AE%89%E8%A3%85airgo%E6%A0%B8%E5%BF%83)
使用debian，ununtu，centos系统，执行以下命令，根据提示安装AirGo核心

bash <(curl -Ls https://raw.githubusercontent.com/ppoonk/AirGo/main/server/scripts/install.sh)


我输完命令之后无法安装 也无法停止运行
显示  AirGo-panel 管理脚本
  当前版本：
  最新版本：0.0.2

  状态： 未安装    已运行
