### ISSUE TITLE
你好 测试中发现几个问题 

### ISSUE THREAD

**Issue by cnmars** [ppoonk/AirGo#8]
1、使用MYSQL作为数据库的时候发现初始化表不全  导致无法打开
2、添加节点的时候 开启中转无法开启   数据库内直接改信息可以打开 但是 中转地址无法填写
3、对接节点后 用户侧节点显示任然是红X  
4、CLASHX无法更新更新出订阅  包括通过和CLASH META  提示   托管配置文件格式不正确: yaml: unmarshal errors:
line 1: cannot unmarshal !!str `dm1lc3M...` into config.RawConfig
暂时就发现这几个问题

**Comment by cnmars** [comment]
有没有电报群 一起测试

**Comment by ppoonk** [comment]
感谢测试反馈，这几个问题稍后我看看。电报被封号，目前无电报。

**Comment by ppoonk** [comment]
> 有没有电报群 一起测试
可以先加我qq，2493733085

**Comment by ppoonk** [comment]
经过排查：

- 使用MYSQL作为数据库的时候发现初始化表不全：已修复
- 添加节点的时候 开启中转无法开启：已修复
- CLASHX无法更新更新出订阅 包括通过和CLASH META 提示 托管配置文件格式不正确：本人在安装clash meta（版本2.8.9.Meta）测试，可以下发并能正确解析，但可能还有未知错误，会继续进行测试

**Comment by cnmars** [comment]
你好订阅不成功的问题我想应该是知道原因了
我测试 删除原有的节点后（先删除商品才可以删除 这里建议增加一个提示 要不有的人会不知道有关联）  增加新的节点  在增加新的商品 新用户在订阅后 发现删除的节点还会出现在订阅当中

**Comment by cnmars** [comment]
vmess://eyJ2IjoiMiIsInBzIjoi5Yiw5pyf5pe26Ze0OjIwMjMtMTItMDIiLCJhZGQiOiJBaXJHbyIsInBvcnQiOiI2NjY2IiwiaWQiOiIwMWE5YzU4MC0xYjMwLTRlNjAtOTlhNS1iN2E2ZTRjOWEyNTUiLCJhaWQiOiIwIiwibmV0Ijoid3MiLCJ0eXBlIjoiIiwiaG9zdCI6IiIsInBhdGgiOiIiLCJ0bHMiOiIiLCJhbHBuIjoiIiwiZnAiOiIiLCJzbmkiOiIifQ==
vmess://eyJ2IjoiMiIsInBzIjoi5Ymp5L2Z5rWB6YePOjEwLjAwR0IiLCJhZGQiOiJBaXJHbyIsInBvcnQiOiI2NjY2IiwiaWQiOiIwMWE5YzU4MC0xYjMwLTRlNjAtOTlhNS1iN2E2ZTRjOWEyNTUiLCJhaWQiOiIwIiwibmV0Ijoid3MiLCJ0eXBlIjoiIiwiaG9zdCI6IiIsInBhdGgiOiIiLCJ0bHMiOiIiLCJhbHBuIjoiIiwiZnAiOiIiLCJzbmkiOiIifQ==
ss://MjAyMi1ibGFrZTMtY2hhY2hhMjAtcG9seTEzMDU6VUhwcFNGaFBTMUJIVGtWMFpsTlNWVVZ3Wm01dWRVVnNla1ZzVG5Ob04wZz06TURGaE9XTTFPREF0TVdJek1DMDBaVFl3TFRrNVlUVXRZamRoTm1VMFl6bGhNalUx@gddd.baidu.com:45222


VMESS是搭建后自带过来的  我删除后增加了ss节点 但是在测试购买后 删除的节点还会出现 在订阅当中

**Comment by ppoonk** [comment]
> 你好订阅不成功的问题我想应该是知道原因了 我测试 删除原有的节点后（先删除商品才可以删除 这里建议增加一个提示 要不有的人会不知道有关联） 增加新的节点 在增加新的商品 新用户在订阅后 发现删除的节点还会出现在订阅当中

ok，收到，我修改看看

**Comment by cnmars** [comment]
找到问题了 sub_service.go  这个文件里会默认插入第一节点第二节点 注释相关代码 没有发现有别的节点  
还发现一个问题  之前CLASH 用CLASH META订阅 无法成功 提示不支持相关加密 发现使用chacha20-poly1305会失败 前端改成这个chacha20-ietf-poly1305 好了   通用的订阅还是不成功  还有我看有电报频道了 电报多少你 我找你

**Comment by ppoonk** [comment]
> 找到问题了 sub_service.go 这个文件里会默认插入第一节点第二节点 注释相关代码 没有发现有别的节点 还发现一个问题 之前CLASH 用CLASH META订阅 无法成功 提示不支持相关加密 发现使用chacha20-poly1305会失败 前端改成这个chacha20-ietf-poly1305 好了 通用的订阅还是不成功 还有我看有电报频道了 电报多少你 我找你

感谢测试，电报群组就能找我。
